# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NetworkViewer' do
  use_frameworks!
	 pod 'Alamofire', '~> 4.5'
   pod 'SwiftyJSON'
	 pod 'SVProgressHUD'
  target 'NetworkViewerTests' do
    inherit! :search_paths
  end

  target 'NetworkViewerUITests' do
    inherit! :search_paths
  end
end
